services:
  - type: web
    name: antony-personal-stremio
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CONFIG_SECRET
        generateValue: true
