"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const {URL}=require("url");
const {addonBuilder,getRouter}=require("stremio-addon-sdk");
const ROOT=__dirname,DATA=path.join(ROOT,"data"),CF=path.join(DATA,"config.json"),SF=path.join(DATA,"state.json");
fs.mkdirSync(DATA,{recursive:true});
const DEF={port:+process.env.PORT||10000,tmdbApiKey:"",stremioAuthKey:"",stremioEmail:"",tmdbMinRating:7,tmdbMinVotes:1000,yearMin:1990,yearMax:new Date().getFullYear(),runtimeMin:0,runtimeMax:0,excludeGenres:["Horror"],maxResults:24,useWatchedExclusion:true,useLikes:true,useHearts:true,excludeCancelledSeries:true,allowOngoingSeries:true};
const STATE={featureWeights:{},positiveItems:{},lastSync:null};
const read=(f,d)=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return d}};
const baseCfg=()=>({...DEF,...read(CF,{})});
const state=()=>read(SF,STATE);
const save=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2),{mode:0o600});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function secret(){return process.env.CONFIG_SECRET||"local-development-secret-change-me"}
function packConfig(c){const iv=crypto.randomBytes(12),key=crypto.createHash("sha256").update(secret()).digest(),x=crypto.createCipheriv("aes-256-gcm",key,iv);const body=Buffer.concat([x.update(JSON.stringify(c),"utf8"),x.final()]),tag=x.getAuthTag();return Buffer.concat([iv,tag,body]).toString("base64url")}
function unpackConfig(token){try{const b=Buffer.from(token,"base64url"),iv=b.subarray(0,12),tag=b.subarray(12,28),body=b.subarray(28),key=crypto.createHash("sha256").update(secret()).digest(),x=crypto.createDecipheriv("aes-256-gcm",key,iv);x.setAuthTag(tag);return JSON.parse(Buffer.concat([x.update(body),x.final()]).toString("utf8"))}catch{return null}}
async function api(method,body){const r=await fetch(`https://api.strem.io/api/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||j.error)throw Error(String(j.error||`HTTP ${r.status}`));return j.result??j}
async function login(email,password){const x=await api("login",{type:"Login",email,password,facebook:false});if(!x?.authKey)throw Error("Stremio n'a pas fourni d'AuthKey");return x.authKey}
const arr=x=>Array.isArray(x)?x:Array.isArray(x?.result)?x.result:Array.isArray(x?.items)?x.items:[];
const imdb=x=>typeof(x?._id||x?.id)==="string"&&/^tt\d+$/.test(x._id||x.id)?(x._id||x.id):null;
async function library(key){if(!key)return[];try{const m=await api("datastoreMeta",{authKey:key,collection:"libraryItem"});const ids=arr(m).map(x=>typeof x==="string"?x:x?._id||x?.id).filter(Boolean),out=[];if(ids.length){for(let i=0;i<ids.length;i+=100)out.push(...arr(await api("datastoreGet",{authKey:key,collection:"libraryItem",ids:ids.slice(i,i+100),all:false})));return out}return arr(await api("datastoreGet",{authKey:key,collection:"libraryItem",ids:[],all:true}))}catch(e){console.warn("Stremio sync:",e.message);return[]}}
function feedback(item){const id=imdb(item);if(!id)return null;const vals=[item.rating,item.rated,item.ratingValue,item.like,item.love,item.state?.rating,item.state?.rated,item.state?.ratingValue,item.state?.like,item.state?.love];for(const v of vals){if(v===true)return{id,type:"like"};const t=typeof v==="string"?v.toLowerCase():v&&typeof v==="object"?String(v.type||v.value||v.name||"").toLowerCase():"";if(["like","liked","thumbs-up","thumbsup"].includes(t))return{id,type:"like"};if(["love","loved","heart"].includes(t))return{id,type:"heart"};if(typeof v==="number"){if(v>=2)return{id,type:"heart"};if(v===1)return{id,type:"like"}}}return null}
async function sync(c){const s=state(),watched=new Set;if(!c.stremioAuthKey)return watched;for(const item of await library(c.stremioAuthKey)){const id=imdb(item);if(!id)continue;const st=item.state||{};if(c.useWatchedExclusion&&(st.flaggedWatched===1||st.watched===true||st.isWatched===true||(typeof st.watched==="number"&&st.watched>0)))watched.add(id);const fb=feedback(item);if(fb&&((fb.type==="like"&&c.useLikes)||(fb.type==="heart"&&c.useHearts)))s.positiveItems[id]=fb.type}s.lastSync=new Date().toISOString();save(SF,s);return watched}
async function tmdb(ep,p,c){if(!c.tmdbApiKey)throw Error("TMDB API key manquante");const u=new URL(`https://api.themoviedb.org/3/${ep}`);for(const[k,v]of Object.entries(p))if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v));u.searchParams.set("api_key",c.tmdbApiKey);const r=await fetch(u);if(!r.ok)throw Error(`TMDB HTTP ${r.status}`);return r.json()}
function quality(r,v,m){const R=+r||0,V=+v||0,M=Math.max(1,+m||1),C=7;return V/(V+M)*R+M/(V+M)*C}
const initial={genres:{Adventure:1.25,Fantasy:1.25,"Science Fiction":1.2,Action:1.05,Drama:1,Thriller:.95,History:1.15,War:1.15,Crime:.95,Mystery:.95},themes:{epic:1.2,"political intrigue":1.2,"power struggle":1.2,revenge:1.15,ambition:1.1,transformation:1.05,survival:1,dystopia:1,space:.95,historical:1.1},avoid:{Horror:-2.5}};
function score(d,c,s){let z=quality(d.vote_average,d.vote_count,c.tmdbMinVotes)*.9+Math.log10(1+(+d.vote_count||0))*.35;for(const g of d.genres||[]){z+=initial.genres[g.name]||0;z+=initial.avoid[g.name]||0;z+=+(s.featureWeights[`genre:${g.name}`]||0)}for(const k of d.keywords?.keywords||[]){const n=String(k.name||"").toLowerCase();for(const[t,w]of Object.entries(initial.themes))if(n.includes(t)||t.includes(n))z+=w;z+=+(s.featureWeights[`kw:${k.name}`]||0)}const f=s.positiveItems[d.imdb_id];if(f==="heart")z+=6;else if(f==="like")z+=3;return z}
async function discover(type,c){const watched=await sync(c),ep=type==="movie"?"discover/movie":"discover/tv",cand=[];for(let page=1;page<=4;page++){const p={language:"en-US",sort_by:"popularity.desc",page,vote_average_gte:c.tmdbMinRating,vote_count_gte:c.tmdbMinVotes};if(type==="movie"){p.primary_release_date_gte=`${c.yearMin}-01-01`;p.primary_release_date_lte=`${c.yearMax}-12-31`}else{p.first_air_date_gte=`${c.yearMin}-01-01`;p.first_air_date_lte=`${c.yearMax}-12-31`}cand.push(...(await tmdb(ep,p,c)).results||[])}const seen=new Set(),ds=[],ex=new Set(c.excludeGenres.map(x=>x.toLowerCase()));for(const x of cand){if(seen.has(x.id)||ds.length>=90)continue;seen.add(x.id);try{const d=await tmdb(`${type==="movie"?"movie":"tv"}/${x.id}`,{language:"en-US",append_to_response:"keywords,external_ids"},c),id=d.imdb_id||d.external_ids?.imdb_id;if(!id||(c.useWatchedExclusion&&watched.has(id)))continue;if((d.genres||[]).some(g=>ex.has(String(g.name).toLowerCase())))continue;if(type==="series"&&c.excludeCancelledSeries&&d.status==="Canceled")continue;if(c.runtimeMin&&d.runtime&&d.runtime<c.runtimeMin)continue;if(c.runtimeMax&&d.runtime&&d.runtime>c.runtimeMax)continue;d.imdb_id=id;d._score=score(d,c,state());ds.push(d)}catch{}}ds.sort((a,b)=>b._score-a._score);return ds.slice(0,c.maxResults).map(d=>({id:d.imdb_id,type,name:d.title||d.name,poster:d.poster_path?`https://image.tmdb.org/t/p/w500${d.poster_path}`:undefined,background:d.backdrop_path?`https://image.tmdb.org/t/p/w1280${d.backdrop_path}`:undefined,description:d.overview||"",releaseInfo:String(d.release_date||d.first_air_date||"").slice(0,4),imdbRating:d.vote_average!=null?Number(d.vote_average).toFixed(1):undefined,genres:(d.genres||[]).map(g=>g.name)}))}
const manifest={id:"com.antony.personalrecommendations",version:"0.2.0",name:"🎯 Antony — Personal Recommendations",description:"Catalogue personnel dynamique basé sur ton profil, tes appréciations Stremio et TMDB.",resources:["catalog","meta"],types:["movie","series"],idPrefixes:["tt"],catalogs:[{type:"movie",id:"antony_movies",name:"🎯 Antony — Films"},{type:"series",id:"antony_series",name:"🎯 Antony — Séries"}],behaviorHints:{configurable:true,configurationRequired:true}};
function page(req){const u=new URL(req.url,`http://${req.headers.host||"localhost"}`),host=u.host;const c=baseCfg();return `<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Antony — Personal Recommendations</title><style>body{font-family:system-ui;background:#111;color:#eee;max-width:760px;margin:25px auto;padding:0 18px}section{background:#1b1b1b;padding:18px;border-radius:12px;margin:14px 0}label{display:block;margin:10px 0 5px}input{width:100%;box-sizing:border-box;padding:10px;border-radius:7px;border:1px solid #444;background:#222;color:#fff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.check{display:flex;gap:8px}.check input{width:auto}button{padding:12px 18px;border:0;border-radius:8px;font-weight:700;width:100%}.note{opacity:.75;font-size:.9em}</style><body><h1>🎯 Antony</h1><p>Configure ton catalogue personnel, puis installe-le directement dans Stremio.</p><form method="post" action="/config/save"><section><h2>Connexions</h2><label>TMDB API key *</label><input name="tmdbApiKey" type="password" required value="${esc(c.tmdbApiKey)}"><label>Stremio AuthKey</label><input name="stremioAuthKey" type="password" value="${esc(c.stremioAuthKey)}"><p class="note">Tu peux utiliser un AuthKey plutôt que ton mot de passe. Ne m'envoie jamais ces clés dans le chat.</p></section><section><h2>Filtres</h2><div class="grid"><div><label>Note minimale</label><input name="tmdbMinRating" type="number" min="0" max="10" step=".1" value="${c.tmdbMinRating}"></div><div><label>Votes minimum</label><input name="tmdbMinVotes" type="number" min="0" step="100" value="${c.tmdbMinVotes}"></div><div><label>Année min.</label><input name="yearMin" type="number" value="${c.yearMin}"></div><div><label>Année max.</label><input name="yearMax" type="number" value="${c.yearMax}"></div><div><label>Durée min.</label><input name="runtimeMin" type="number" min="0" value="${c.runtimeMin}"></div><div><label>Durée max.</label><input name="runtimeMax" type="number" min="0" value="${c.runtimeMax}"></div></div><label>Genres à exclure</label><input name="excludeGenres" value="${esc(c.excludeGenres.join(", "))}"></section><section><h2>Apprentissage</h2><label class="check"><input name="useWatchedExclusion" type="checkbox" ${c.useWatchedExclusion?"checked":""}> Exclure les contenus déjà vus</label><label class="check"><input name="useLikes" type="checkbox" ${c.useLikes?"checked":""}> Utiliser les 👍</label><label class="check"><input name="useHearts" type="checkbox" ${c.useHearts?"checked":""}> Utiliser les ❤️</label><label class="check"><input name="excludeCancelledSeries" type="checkbox" ${c.excludeCancelledSeries?"checked":""}> Exclure les séries annulées</label></section><button>Enregistrer et obtenir le bouton d'installation</button></form></body></html>`}
function parse(req){return new Promise((ok,bad)=>{let d="";req.on("data",x=>d+=x);req.on("end",()=>ok(new URLSearchParams(d)));req.on("error",bad)})}
async function saveConfig(req,res){try{const p=await parse(req);const key=p.get("stremioAuthKey")||"";if(!key)throw Error("Pour cette version hébergée, renseigne ton Stremio AuthKey. Le mot de passe n'est pas demandé ici.");const c={...DEF,tmdbApiKey:p.get("tmdbApiKey")||"",stremioAuthKey:key,tmdbMinRating:+p.get("tmdbMinRating")||7,tmdbMinVotes:+p.get("tmdbMinVotes")||1000,yearMin:+p.get("yearMin")||1990,yearMax:+p.get("yearMax")||new Date().getFullYear(),runtimeMin:+p.get("runtimeMin")||0,runtimeMax:+p.get("runtimeMax")||0,excludeGenres:(p.get("excludeGenres")||"").split(",").map(x=>x.trim()).filter(Boolean),useWatchedExclusion:p.has("useWatchedExclusion"),useLikes:p.has("useLikes"),useHearts:p.has("useHearts"),excludeCancelledSeries:p.has("excludeCancelledSeries")};const token=packConfig(c);const host=new URL(req.headers.referer||"http://localhost").origin;const manifestUrl=`${host}/u/${token}/manifest.json`;res.writeHead(200,{"content-type":"text/html; charset=utf-8"});res.end(`<!doctype html><meta name="viewport" content="width=device-width"><style>body{font-family:system-ui;background:#111;color:#eee;max-width:650px;margin:40px auto;padding:20px}a{display:block;background:#fff;color:#111;text-align:center;padding:16px;border-radius:10px;font-weight:700;text-decoration:none;margin:20px 0}</style><h1>Configuration terminée</h1><p>Le bouton ci-dessous ouvre Stremio et installe ton catalogue.</p><a href="stremio://${host.replace(/^https?:\/\//,"")}/u/${token}/manifest.json">Installer dans Stremio</a><p>Si Stremio ne s'ouvre pas, copie ce lien dans le navigateur du téléphone : <code>${esc(manifestUrl)}</code></p>`)}catch(e){res.writeHead(400,{"content-type":"text/plain; charset=utf-8"});res.end("Erreur: "+e.message)}}
function cfgFromPath(pathname){const m=pathname.match(/^\/u\/([^/]+)\//);return m?unpackConfig(m[1]):null}
let REQUEST_CONFIG=null;
async function main(){const b=new addonBuilder(manifest);b.defineCatalogHandler(async a=>{try{return{metas:await discover(a.type,a.config||REQUEST_CONFIG||baseCfg()),cacheMaxAge:900,staleRevalidate:1800}}catch(e){console.error(e);return{metas:[]}}});b.defineMetaHandler(async a=>{try{const c=a.config||REQUEST_CONFIG||baseCfg(),d=await tmdb(`${a.type==="series"?"tv":"movie"}/${a.id}`,{language:"en-US"},c);return{meta:{id:a.id,type:a.type,name:d.title||d.name,poster:d.poster_path?`https://image.tmdb.org/t/p/w500${d.poster_path}`:undefined,background:d.backdrop_path?`https://image.tmdb.org/t/p/w1280${d.backdrop_path}`:undefined,description:d.overview||"",releaseInfo:String(d.release_date||d.first_air_date||"").slice(0,4),imdbRating:d.vote_average!=null?Number(d.vote_average).toFixed(1):undefined,genres:(d.genres||[]).map(g=>g.name)}}}catch{return{meta:null}}});const router=getRouter(b.getInterface()),port=+process.env.PORT||+baseCfg().port||10000,host=process.env.HOST||"0.0.0.0";http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||"localhost"}`);if(u.pathname==="/health"){res.writeHead(200);return res.end("ok")}if(u.pathname==="/configure"){res.writeHead(200,{"content-type":"text/html; charset=utf-8"});return res.end(page(req))}if(u.pathname==="/config/save"&&req.method==="POST")return saveConfig(req,res);const tokenCfg=cfgFromPath(u.pathname);if(u.pathname.endsWith("/manifest.json")&&tokenCfg){res.writeHead(200,{"content-type":"application/json"});return res.end(JSON.stringify(manifest))}if(tokenCfg&&(u.pathname.includes("/catalog/")||u.pathname.includes("/meta/"))){const original=req.url;req.url=u.pathname.replace(/^\/u\/[^/]+/,"")+u.search;const old=req.headers["x-stremio-config"];req.headers["x-stremio-config"]=JSON.stringify(tokenCfg);try{const wrapped={...req};Object.defineProperty(wrapped,"url",{value:req.url});return routerWithConfig(router,wrapped,res,tokenCfg)}finally{if(old===undefined)delete req.headers["x-stremio-config"];else req.headers["x-stremio-config"]=old}}if(u.pathname==="/manifest.json"){res.writeHead(200,{"content-type":"application/json"});return res.end(JSON.stringify(manifest))}res.end("Antony Personal Recommendations — /configure")}).listen(port,host,()=>console.log(`Configure: http://${host}:${port}/configure`))}
async function routerWithConfig(router,req,res,c){const original=req.url;const cfg=c;const origHeaders=req.headers;req.headers={...origHeaders};try{const old=REQUEST_CONFIG;REQUEST_CONFIG=cfg;const r=router(req,res);if(r&&typeof r.then==="function")await r;REQUEST_CONFIG=old}catch(e){console.error(e);if(!res.headersSent){res.writeHead(500);res.end("Addon error")}}}
main().catch(e=>{console.error(e);process.exit(1)})
